# Full documentation: https://hweippy.gitbook.io/copychain/configuration/parameters

private_key = "my_wallet.copychain.json"
copy_pubkeys = ["..."]  # define which wallet your want to copy here

[reading]
rpc_url = "..."
grpc_url = "..."

[sending.spam]
urls = ["..."]

[sending.jito]
auth_keys = ["..."]        # your jito UUID here
fail_if_no_profit = false  # don't fail tx for jito

# Helius and Lunar senders don't require an API key (yet)

[[sending.vendors]]
vendor = "helius"
nonces_id = "main"

[[sending.vendors]]
vendor = "lunar"
nonces_id = "main"

# If you have a Temporal API key, uncomment the section below

# [[sending.vendors]]
# vendor = "temporal"
# auth_keys = ["..."]
# nonces_id = "main"

[[nonces]]
id = "main"
accounts = [
    "...",
    "...",
]
