rpc_url = "https://solana-rpc.publicnode.com"
grpc_url = "https://solana-yellowstone-grpc.publicnode.com" 
grpc_token = "..." #  Grab your free token here https://www.allnodes.com/publicnode 
grpc_compression = "none"