my_pubkey = "xxx"    # (optional) your wallet pubkey

grpc_url = "https://solana-yellowstone-grpc.publicnode.com" 
rpc_url = "https://solana-rpc.publicnode.com"

copy_all = true      # monitor all wallets
