[bot]
merge_mints = true
compute_unit_limit = 600_000
skip_ata_creation = true

[rpc]
url = "" # <<<<<<<<<< Your read rpc URL here

[spam]
enabled = true
sending_rpc_urls = [""] # <<<<<<<<<< Your send rpc URL here
compute_unit_price = { strategy = "Random", from = 1, to = 1, count = 1 }
max_retries = 0

[jito]
enabled = true
block_engine_urls = [
  "https://ny.mainnet.block-engine.jito.wtf/api/v1",
  "https://tokyo.mainnet.block-engine.jito.wtf/api/v1",
  "https://slc.mainnet.block-engine.jito.wtf/api/v1",
  "https://frankfurt.mainnet.block-engine.jito.wtf/api/v1",
  "https://amsterdam.mainnet.block-engine.jito.wtf/api/v1",
  "https://london.mainnet.block-engine.jito.wtf/api/v1",
  "https://singapore.mainnet.block-engine.jito.wtf/api/v1",
  "https://dublin.mainnet.block-engine.jito.wtf/api/v1",
]
use_separate_tip_account = false
uuid = ""  # <<<<<<<<<< Your jito uuid here
no_failure_mode = true
block_engine_strategy = "AllAtOnce"
tip_config = { strategy = "Random", from = 0, to = 0, count = 1 }

[[sending_venders.sending_vender]]
enabled = true
tip_amount = { strategy = "Random", from = 0, to = 0, count = 1 }
compute_unit_price = { strategy = "Random", from = 0, to = 0, count = 1 }
urls = [
    "http://ewr-sender.helius-rpc.com/fast?swqos_only=true",
    "http://slc-sender.helius-rpc.com/fast?swqos_only=true",
    "http://ewr-sender.helius-rpc.com/fast?swqos_only=true",
    "http://lon-sender.helius-rpc.com/fast?swqos_only=true",
    "http://fra-sender.helius-rpc.com/fast?swqos_only=true",
    "http://ams-sender.helius-rpc.com/fast?swqos_only=true",
    "http://sg-sender.helius-rpc.com/fast?swqos_only=true",
    "http://tyo-sender.helius-rpc.com/fast?swqos_only=true",
]
tip_accounts = [
  "4ACfpUFoaSD9bfPdeu6DBt89gB6ENTeHBXCAi87NhDEE",
  "D2L6yPZ2FmmmTKPgzaMKdhu6EWZcTpLy1Vhx8uvZe7NZ",
  "9bnz4RShgq1hAnLnZbP8kbgBg1kEmcJBYQq3gQbmnSta",
  "5VY91ws6B2hMmBFRsXkoAAdsPHBJwRfBht4DXox3xkwn",
  "2nyhqdwKcJZR2vcqCyrYsaPVdAnFoJjiksCXJ7hfEYgD",
  "2q5pghRs6arqVjRvT5gfgWfWcHWmw1ZuCzphgd5KfWGJ",
  "wyvPkWjVZz1M8fHQnMMCDTQDbkManefNNhweYk5WkcF",
  "3KCKozbAaF75qEU33jtzozcJ29yJuaLJTy2jFdzUY8bT",
  "4vieeGHPYPG2MmyPRcYjdiDmmhN3ww7hsFNap8pVN3Ey",
  "4TQLFNWK8AovT1gFvda5jfw2oJeRMKEmw7aH6MGBJ3or",
]
no_failure_mode = false
sending_strategy = "AllAtOnce"  # AllAtOnce or OneByOne
request_params = { skipPreflight = true }

[flashloan]
enabled = true

[wallet]
